In [2]:
import pandas as pd

ratings = pd.read_csv(
    "ml-1m/ratings.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["userId", "movieId", "rating", "timestamp"],
    header=None
)

movies = pd.read_csv(
    "ml-1m/movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movieId", "title", "genres"],
    header=None
)

In [3]:
movies.head()

   movieId                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [4]:
ratings.head()

   userId  movieId  rating  timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [5]:
movies["content"] = movies["title"] + " " + movies["genres"].str.replace("|", " ")
movies.head()

,movieId,title,genres,content
0,1,Toy Story (1995),Animation|Children's|Comedy,Toy Story (1995) Animation Children's Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy,Jumanji (1995) Adventure Children's Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men (1995) Comedy Romance
3,4,Waiting to Exhale (1995),Comedy|Drama,Waiting to Exhale (1995) Comedy Drama
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II (1995) Comedy

In [6]:
data = ratings.merge(movies, on="movieId")
data.head(20)

,userId,movieId,rating,timestamp,title,genres,content
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,One Flew Over the Cuckoo's Nest (1975) Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,James and the Giant Peach (1996) Animation Chi...
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,My Fair Lady (1964) Musical Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,Erin Brockovich (2000) Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,"Bug's Life, A (1998) Animation Children's Comedy"
5,1,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,"Princess Bride, The (1987) Action Adventure Co..."
6,1,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama,Ben-Hur (1959) Action Adventure Drama
7,1,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama,"Christmas Story, A (1983) Comedy Drama"
8,1,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,Snow White and the Seven Dwarfs (1937) Animati...
9,1,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,"Wizard of Oz, The (1939) Adventure Children's ..."
10,1,595,5,978824268,Beauty and the Beast (1991),Animation|Children's|Musical,Beauty and the Beast (1991) Animation Children...
11,1,938,4,978301752,Gigi (1958),Musical,Gigi (1958) Musical
12,1,2398,4,978302281,Miracle on 34th Street (1947),Drama,Miracle on 34th Street (1947) Drama
13,1,2918,4,978302124,Ferris Bueller's Day Off (1986),Comedy,Ferris Bueller's Day Off (1986) Comedy
14,1,1035,5,978301753,"Sound of Music, The (1965)",Musical,"Sound of Music, The (1965) Musical"
15,1,2791,4,978302188,Airplane! (1980),Comedy,Airplane! (1980) Comedy
16,1,2687,3,978824268,Tarzan (1999),Animation|Children's,Tarzan (1999) Animation Children's
17,1,2018,4,978301777,Bambi (1942),Animation|Children's,Bambi (1942) Animation Children's
18,1,3105,5,978301713,Awakenings (1990),Drama,Awakenings (1990) Drama
19,1,2797,4,978302039,Big (1988),Comedy|Fantasy,Big (1988) Comedy Fantasy

In [7]:
documents = movies['content'].fillna("").tolist()
print(type(documents))
print(documents[:10])

<class 'list'>
["Toy Story (1995) Animation Children's Comedy", "Jumanji (1995) Adventure Children's Fantasy", 'Grumpier Old Men (1995) Comedy Romance', 'Waiting to Exhale (1995) Comedy Drama', 'Father of the Bride Part II (1995) Comedy', 'Heat (1995) Action Crime Thriller', 'Sabrina (1995) Comedy Romance', "Tom and Huck (1995) Adventure Children's", 'Sudden Death (1995) Action', 'GoldenEye (1995) Action Adventure Thriller']

In [8]:
tokenized_docs = []

for doc in documents:
    doc = doc.lower()
    doc = doc.replace("(","").replace(")","")
    doc = doc.replace(",","").replace(".","")
    doc = doc.replace("'","")
    doc = doc.split()
    # print(words)
    # for word in words:
        # tokenizated_docs.append(word)
    tokenized_docs.append(doc)

print(tokenized_docs[:20])
print(len(tokenized_docs))

[['toy', 'story', '1995', 'animation', 'childrens', 'comedy'], ['jumanji', '1995', 'adventure', 'childrens', 'fantasy'], ['grumpier', 'old', 'men', '1995', 'comedy', 'romance'], ['waiting', 'to', 'exhale', '1995', 'comedy', 'drama'], ['father', 'of', 'the', 'bride', 'part', 'ii', '1995', 'comedy'], ['heat', '1995', 'action', 'crime', 'thriller'], ['sabrina', '1995', 'comedy', 'romance'], ['tom', 'and', 'huck', '1995', 'adventure', 'childrens'], ['sudden', 'death', '1995', 'action'], ['goldeneye', '1995', 'action', 'adventure', 'thriller'], ['american', 'president', 'the', '1995', 'comedy', 'drama', 'romance'], ['dracula:', 'dead', 'and', 'loving', 'it', '1995', 'comedy', 'horror'], ['balto', '1995', 'animation', 'childrens'], ['nixon', '1995', 'drama'], ['cutthroat', 'island', '1995', 'action', 'adventure', 'romance'], ['casino', '1995', 'drama', 'thriller'], ['sense', 'and', 'sensibility', '1995', 'drama', 'romance'], ['four', 'rooms', '1995', 'thriller'], ['ace', 'ventura:', 'when', 'nature', 'calls', '1995', 'comedy'], ['money', 'train', '1995', 'action']]
3883

In [9]:
vocab = set()
for doc in tokenized_docs:
    vocab.update(doc)
print(vocab)
print(len(vocab))

{'babes', 'jones', 'preferred', 'heroes', 'ss', 'godzilla', 'gigolo', 'borrowers', 'coup', 'kentucky', 'fresh', 'deux', 'bilder', '45', 'splendor', 'diario', 'wallace', 'spinal', 'gump', 'sources', 'overdrive', 'joseph', 'sous-sol', 'englishman', 'ark', 'caballeros', 'they?', 'mountains', 'general', 'event', 'atlantic', 'mine', 'sin', 'lengua', 'bean', 'chariots', 'free', 'laid', 'pole', 'kama', 'metro', 'vagabond', 'thieves', 'twisted', 'trading', 'kidnapped', 'boricuas', 'specials', 'maine', 'dictator', 'smell', 'marnie', 'houseguest', 'razors', 'jardin', 'autoportrait', 'impostors', 'kim', 'basquiat', 'ninotchka', 'star', 'vampires', 'minnie', 'seabees', 'ensangrentada', 'mom', 'saucers', 'lay', 'lyric', 'cider', 'bell', 'barcelona', 'iron', 'reazione', 'vinny', 'palm', 'jerky', '34th', 'zero', 'sundance', 'palookaville', 'clockers', 'johnson', 'mall', 'dvadesetiot', 'disturbing', 'empty', 'northwest', '42', 'kinky', 'existenz', 'grauens', 'cant', 'letter', 'notting', 'records', 'bites', 'crucible', 'waking', 'lagoon', 'presents:', 'resurrection', 'arthurs', 'fistful', 'elmos', 'rage:', 'avenger', 'favor', 'audrey', 'asfour', 'evil', 'suspicion', '1951', 'exotica', 'fairytale:', 'mondo', 'quarry', '7th', 'cinema', 'even', 'diggers:', 'morant', 'v', 'lords', 'catastrophes', 'kid', 'birch', 'student', 'foot', 'cérémonie', 'odyssey', 'vermeers', 'astronauts', 'slc', 'crisis', 'milo', 'loi', 'città', 'journal', 'lotto', 'chop', 'october', 'and', 'zorro', 'ge', 'neng', 'swimming', 'coma', 'year', 'executive', 'do', 'american', 'casa', 'drunks', 'yards', 'creeps', 'backdraft', 'flintstones', 'opposite', 'producers', 'browns', 'closer', 'bountiful', 'power', 'holiday', 'campus', 'notti', 'spy', 'amants', 'east-west', 'glass', 'kings', 'kingpin', '1973', 'azucar', 'bernies', 'sadness', 'net', 'manon', 'after:', 'public', 'skip', 'patriot', 'months', 'four', 'army', 'stacys', 'right', 'femme', 'empire', 'carrington', 'sunrise', '1991', 'clay', 'nave', 'presidio', 'machine', 'against', 'shots', 'pasqualino', 'wally', 'travels', 'turbo:', 'animal', 'spattered', 'moonraker', 'balloon', 'got', 'mother', 'kane', 'renaissance', 'cocoon:', 'swept', 'places', 'batman:', 'maîtres', 'quatermass', 'shooter', '1932', 'fling', 'cabin', 'boiler', 'sydney', 'squanto:', 'christ', 'enchanted', 'born', 'payne', 'perez', 'bure', 'zahlt', 'force', 'damage', 'una', 'getting', 'carnosaur', 'belly', 'uninvited', 'knockout', 'what', 'steve', 'cowboy', 'convoyeurs', 'below', 'civilization', 'book:', 'amargo', 'wyn', 'tuned', 'picture', 'remember', 'warhols', 'follow', 'lisa', 'marshalls', 'forty', 'butcher', 'heidi', 'saints', 'cobb', 'darby', 'sunday', 'speriamo', 'greenwich', 'spinnen', 'jacket', 'love:', 'retro', 'raise', 'oxygen', 'jackson', 'conformista', 'hunt', 'matchmaker', 'stop', 'dolittle', 'montana', 'vanzetti', 'lees', 'myself', 'three', 'triad', 'wind', 'fear', 'spirits', 'det', 'great?', 'interiors', 'horses', 'braindead', 'murder!', 'rudy', 'stripes', 'shining', 'wrong', 'flatliners', 'tic', 'cléo', 'dangerously', 'wars:', 'bonnie', 'may', 'pieces', 'bent', 'file', 'thunder', 'indiana', 'theory', 'pinocchio', 'through', 'shuang', 'affair', 'garden', 'malli', 'lion', 'shoot', 'seeking', 'è', 'coneheads', 'brasil', 'entrapment', '1921', 'candleshoe', '2000', 'neverending', 'shop', 'crush', 'rangers', 'catfish', 'there', 'news', 'louise', 'akira', 'carolina', 'mononoke', 'mépris', 'turbulence', 'alive', 'teenage', 'supernova', 'kissing', 'platoon', 'porter', 'lughnasa', 'heinleins', 'wicked', 'bolle', 'meet', 'bushwhacked', 'earp', '302', 'lucie', 'rêvée', 'liebelei', 'dont', 'screen', 'millionaire', 'red', 'fine', 'jacobs', 'alan', 'navarone', 'guts', 'operation', '1600', 'octane', 'milagros', 'care', 'strip', 'threesome', 'cross', 'kronos', 'played', 'sunshine', '13th:', 'cuckoos', 'candyman:', 'donnie', 'saddles', 'bu', 'crocodiles', 'english', 'cousin', 'bedrooms', 'encino', 'dorothy', 'toulons', 'band', 'acid', 'nuit', 'breathless', 'rescuers', 'limey', 'underground', 'inferno', 'costello', 'board', 'mirage', 'rosemarys', 'country', 'rubicon', 'twister', 'common', 'shagged', 'sorghum', 'bride', 'happened', 'icon', 'anchors', 'viventi', 'chinatown', 'out-of-towners', 'eye', 'siege', 'senior', 'assassination', 'xiu', 'rainbow', 'slayer', 'serenade', 'prendront', 'rush', 'sarajevo', 'champions', 'illusions', 'family', 'tarzan', 'woolf?', 'tiffanys', 'claras', 'horse', 'retrouvé', 'misérables', 'diaries', 'sorcerer', 'qui', 'marchait', 'parallel', 'l', 'umbrellas', 'home:', 'boca', 'nebula', 'hard', 'shorty', 'tingle', 'cavo', 'vampyros', 'canyon', 'trans', 'open', 'clue', 'grifters', 'pianista', 'fabulous', 'raining', 'own', 'matilda', 'jr', 'felicias', 'amateur', 'tales', 'doors', 'som', 'jerk', 'idaho', 'claus:', 'titan', 'liberty', 'wanted', 'now', 'thunderball', 'horror', 'bunch', 'ape', 'honeymoon', 'saves', 'thief', 'nuke', 'marigolds', 'melvin', 'conspiracy', 'insects', 'dragons', 'saturday', 'shaft', 'tokyo', 'primary', 'rocket', 'jamaica', 'erin', 'brigade', 'if', 'pop', 'month', '1941', 'met', 'box', 'lost:', 'shadows', 'dancer', 'heretic', 'someone', 'longer', 'grosse', 'dello', 'vermont', 'husband', 'losing', 'cavalcade', 'sophies', 'named', 'new', 'della', 'snatcher', 'rob', 'redemption', 'ii:', 'music', 'marlene', 'blechtrommel', 'broken', 'buddha', 'anything', 'pride', 'colors', 'accused', 'them!', 'sum', 'century', 'burnt', 'moll', 'bodyguard', 'soirée', 'metropolis', 'jeopardy', 'iii', 'wife', 'tous', 'bridges', 'romeo', 'fiend', 'withnail', 'dogma', 'laurel', 'yesterday', 'novia', 'above', 'winterbourne', 'fatigue', 'hillbillys', 'penny', 'torn', 'weddings', 'grouchland', 'endearment', 'stargate', 'night', 'nothing', '2010', 'hip-hop', 'meatballs', 'files', 'wish', 'strike!', 'nightmare', 'cherbourg', 'gould', '1940', 'oeil', 'six-string', '8th', 'cyberspace', 'oblivion', 'nel', 'dream', 'gordy', 'woke', 'cutting', 'gazon', 'dersu', 'freak', 'teil:', 'bank', 'filth', 'celebration', 'turkish', 'birdy', 'valour!', 'gilbert', 'birthday', 'cabinet', 'curse', 'bastard', 'bath', 'tommy', 'berlin', 'solari', 'xiong', 'jar', '1936', 'magnolias', 'bleak', 'mary', 'dozhdot', 'consequences', 'candyman', 'plan', 'fled', 'joey', 'nixon', 'importance', 'business', 'wheres', 'drifter', 'underworld', 'step', 'círculo', 'maudit', 'saw', 'elephant', 'hype!', 'shots!', 'still', 'goes', 'carnival', 'heavenly', 'amigos', 'serial', 'dragon', 'simpatico', 'green', 'stalingrad', 'mort', 'eves', 'condo', 'conquest', 'lo', 'vietnam', 'brazil', 'academy', 'ladri', 'giants', 'ozona', 'aristocats', 'crying', 'brava', 'promise', 'muir', 'prey', 'paralyzing', 'twenty-five', '1971', 'says', 'desperately', 'mowgli', 'battling', 'idiots', 'edge', 'lifeforce', 'professor', '2:', 'child', 'haunted', 'bottle', 'paradine', 'hustler', 'smoking', 'substitute', 'videotape', 'loaded', 'essential', 'carnal', 'piranha', 'flamingos', 'roma', 'carter', 'surprise', 'bye', 'monster', 'started', 'inn', 'baraka', 'citizen', 'bless', 'saragossa', 'jason', 'bamboozled', 'placid', 'deuce', 'unforgotten:', 'hui', 'twin', 'pit', 'brown', 'california', 'pail', 'breaker', 'blair', 'catwalk', 'prom', 'willowbrook', 'incredibly', 'macka', 'mass', 'federal', '54', 'sobre', 'goulds', 'willow', 'tampopo', 'oliver', 'female', 'barrels', 'sierra', 'che', 'ayn', 'big', 'happen', 'barneys', 'hip', 'assassin', 'bossa', 'william', '12', '1925', 'abre', 'feast', 'peggy', 'chill', '20', 'poets', '1976', 'without', 'bounty', 'fort', 'daytrippers', 'living', 'sprung', 'blonde', 'singles', 'wonderful', 'aparajito', 'toys', 'careful', 'robinson', 'gillian', 'life!', 'goat', 'dracula:', 'every', 'phenomenon', 'manchu', 'gun:', 'stones', 'amigos!', 'weapon', 'assassins', 'then', 'danger', 'mutters', 'lian', 'browning', 'seduction', 'mussolini', 'pot', 'max', 'detective', 'honigmond', 'leopard', 'richer', 'alien', 'close', 'crows', 'boni', 'tiger', 'lucy', 'town', 'ground', 'buffy', 'awfully', '1945', 'allnighter', 'running', 'deliverance', 'madonna:', 'motel', 'sheep', 'drum', 'crusade', 'butler', 'walking', 'jasons', 'grace', 'original', 'dies', 'debutante', 'spanking', 'wishmaster', 'zbogum', 'excess', 'hendersons', '1988', 'always', 'python', 'body', 'illuminata', 'relic', 'connection', 'drugstore', 'echoes', 'maverick', 'guildenstern', 'ciao', 'opus', 'valley', 'preacher', 'harriet', 'roman', 'mind', 'butch', 'know', 'presidents', 'spice', 'rope', 'jane', 'vienna', '1999', 'cruel', 'f/x', 'horizon', 'underneath', 'single', 'mediterraneo', 'camelot', '&', 'omen', 'motion', 'amos', 'front', 'batch', 'dog', 'beaver', 'pocus', 'sabotage', 'payback', 'bob?', 'bound:', 'separation', 'eds', 'simon', 'bobby', 'beverly', 'possession', 'jericho', 'them', 'gypsies', 'shadowlands', 'chuck', 'greasers', 'legends', 'stir', 'whole', 'fair', 'this', 'kjøtere', 'instinct', 'thousand', 'saboteur', 'ten', 'abominable', 'sugarland', 'sauce', 'hoodlum', 'firestorm', '3d', 'contempt', 'minded', 'detroit', 'cutters', 'duffel', 'cop', 'arachnophobia', 'testimone', 'hood', 'delle', 'acres', 'pet', 'romy', 'poppins', 'ryan', '1938', 'intentions', 'café', 'turned', 'timecop', 'turns', 'undiscovered', 'documentary', 'xiu:', 'wu', 'lightfoot', 'season', 'replacements', 'things', 'lover', 'robocop', 'invitation', 'mchales', 'faculty', 'micheles', 'streets', 'dreamscape', 'suna', 'divorcee', 'deliver', 'leggenda', 'dancemaker', 'number', 'davy', 'jupiters', 'fantasia', 'nettoyage', 'famous', 'seats', 'stein', 'gingerbread', 'bonzai', 'cowboys', 'dantonin', '77', 'smithee', 'fright', 'ilsa', 'deceiver', 'fandango', 'champagne', 'caddyshack', 'potyomkin', 'arizona', 'grit', 'cable', 'day', 'rascals', 'boomerang', 'clan', 'sneakers', 'cement', 'mr', 'bis', 'stuart', 'engel', 'picasso', 'higher', 'lifeboat', 'angustia', 'shoes', 'parents', 'diamonds', 'savior', 'village', 'dautomne', 'sir', 'bedlam', 'virgin', 'hum', 'conformist', 'bed', 'nick', 'charm', 'geronimo:', 'yojimbo', 'relax', 'lowdown', 'see', 'heartbreak', 'crossfire', '1993', 'drink', 'trap', 'cat!', 'china', 'muse', 'dalloway', 'historia', 'could', 'career', 'iris', 'sommeil', 'mega', 'given', 'mixed', 'marvin', 'secreto', 'vertigo', 'trees', 'indian', 'dead:', 'childs', 'bandit', 'flawless', 'thirty-two', 'pajama', 'formidable', 'wirey', 'these', 'calls', 'mister', 'indemnity', 'jump', 'nous', 'hit', 'time', 'werewolf', 'plaid', 'yeller', 'vu', 'celluloid', 'bambi', 'park:', 'insomniac', 'tender', 'brains', 'fantastic', 'adventure', 'beetlejuice', 'sans', 'samurai', 'omega', 'heads', 'farewell', 'yes', 'jeckyll', 'peaks:', 'irene', 'madness', '1934', 'midsummer', '1980', 'catena', 'radioland', 'days', 'tides', 'bigger', 'segno', 'harlem', 'sleeping', 'sisters', 'blackmail', 'mice', 'angry', 'dollars', 'souls', 'crew', 'ci', 'andy', 'odd', 'miss', 'inheritors', 'sweet', 'legs', 'baseketball', 'how', 'duty', 'class', 'jafar', 'fletch', 'tracy', 'defying', 'fury', 'blvd', 'deedles', 'plenty', 'raiders', 'friend', 'chocolate', 'terror', 'lulu', 'jazz', 'manuscript', 'hands', 'collar', 'boat', 'daughters', 'thumb', 'broomsticks', 'learned', 'bedroom', 'kingukongu', 'castle', 'funeral', 'heaven', 'assignment:', 'w', 'cat', 'highway', 'devlin', 'meets', 'week', 'séparation', 'daze', 'actors', 'romance', 'nation', 'tolls', 'make', 'shawshank', 'roof', 'risk', 'dirty', 'completely', 'josey', 'battleship', 'africa', 'suicide', 'clubland', 'khoda', 'ni', 'anguish', 'maybe', 'error', 'bloodline', 'shaggy', 'decision', 'mating', 'city', 'nobodys', 'forest', 'live', 'barefoot', 'knew', 'witch', 'sansar', 'sharks', 'kramer', 'bringing', 'prince', 'creepshow', 'stiff', 'mambo', 'addams', 'suddenly', 'zola', '3-d', 'strangers', '1-900', 'folks', 'grandfather', 'bite', 'cassidy', 'ronin', 'immortality', 'maximum', 'rich', 'raven', 'freedom', 'shallow', 'crazy', 'tin', 'election', 'proposition', 'bitter', 'walk', 'blues', 'paradiso', 'chase', 'powers:', 'alone', 'hamam', 'powder', 'feiying', 'alien:', 'within', 'stop!', 'bio-dome', 'reality', 'hitch-hiker', 'jing', 'elses', 'women', 'generations', 'sonic', 'footloose', 'is', 'monkey', 'volcano', 'mifune', 'father', 'storm', 'sea', 'revolution', 'enterprise', 'calendar', 'all', 'leading', 'unhold', 'endless', 'apple', 'cape', 'u-571', 'eaten', 'wales', 'henrietta', 'illtown', 'arms', 'want', 'oficial', 'thriller', 'bowles', 'prefontaine', 'yi', 'faraway', 'tao', 'can', 'mutant', 'fiction', 'river', 'minister:', 'shakespeare', 'brain', 'pan', '8mm', 'shes', 'over', 'action', '1956', 'sebastian', 'pornographique', 'screwed', 'horatio', '187', 'keiner', 'gentlemans', 'ramirez', 'shines', 'about', '1948', 'mccabe', 'paycock', 'larry', 'dumpling', 'senses', 'magoo', 'aubrac', 'name', 'cleo', 'idle', '1st', 'dugan', '1928', 'apartment', 'bustin', 'juan', 'twelfth', '1922', 'a', 'hollow', 'going', 'castaways', 'charade', 'die', 'quest', 'watching', 'wrath', 'fresa', 'outbreak', 'were', 'fist', 'taking', 'flynt', '1930', 'metroland', 'commitments', 'aces:', 'bonfire', 'goodfellas', 'jour', 'sutra:', 'barb', 'mia', '1919', 'cruise', 'chinois', 'strangelove', 'autopsy', 'bullwinkle', '1989', 'bigalow:', 'map', 'tequila', 'rambo:', 'skin', 'monty', 'arc', 'missing', 'ceux', 'hime', 'unforgiven', 'mir', 'paulie', 'extra-terrestrial', 'jesse', 'wanna', 'gung', 'yellow', 'hood:', 'brasco', 'nellazzurro', 'belgians', 'crna', 'pool', 'christine', 'alabama', 'pelican', 'peacemaker', 'zoe', 'african', 'confidential', 'shadrach', 'bestia', 'mascara', 'buckaroo', 'tashunga', 'hype', 'unknown', 'maude', 'sabrina', 'sword', 'gann', 'nine', 'garcu', 'yue', 'pyromaniacs', 'boiling', 'madagascar', 'drive', 'fear:', '301', 'gladiator', 'ripley', 'vek', 'pesos', 'howard', 'tango', 'cannibal', 'ed', 'wight', 'mission:', 'brooklyn', 'circus', 'eternity', 'access', 'kilimanjaro', 'fella', 'burlesque', 'shrunk', 'prisoner', 'taxi', 'trois', 'couch', 'chasers', 'crockett', 'peking', 'jumanji', 'conan', 'winter', 'past', 'blood', 'm', 'tree', 'ocean', 'phantasm', 'returns', 'hellraiser', 'native', 'alles', 'face/off', 'roxanne', 'priest', 'immortal', 'faithful', 'gets', 'arrow', 'ii', 'saving', 'some', 'hunted', 'among', 'cest', 'fin', 'navy', 'kundun', '5', 'around', 'weint', 'criminals', 'curtain', 'guy', 'shall', 'kagemusha', 'bird', 'abyss', 'volti', 'nightwatch', 'phörpa', 'network', 'juction', 'gong', '1935', 'sorority', 'falling', 'utomlyonnye', 'liar', 'gotten', 'tumbleweeds', 'guilty', 'unstrung', 'mera', 'corner', 'headless', 'awake', 'voleurs', 'down!', 'ville', 'rooms', 'burn', 'topless', 'homeward', 'again', 'lampoons', 'foolish', 'verdict', 'septembre', 'tigger', 'july', 'court', 'forrest', 'reindeer', 'excalibur', 'mulholland', 'poisoners', '1995', 'patient', '1959', 'core', 'poison', 'flight', 'sliding', 'bamba', 'predator', 'evening', 'lost', 'isaiah', 'ran', 'search', 'vista', 'gossip', 'midnight', 'mer', '2001:', '1992', 'gila', 'mankind', 'railroaded!', 'dark', 'smith', 'rouge', 'como', 'ill', 'valiant', 'friday', 'appeal', 'convent', 'liebt', 'ship', 'kozlowski', 'bicentennial', 'loser', 'annihilation', 'ratchet', 'arsenic', 'falls', 'fighter', 'faust', 'ben-hur', 'maurice', 'breaks', 'inspector', 'tea', 'while', 'miami', 'cherry', 'wire', 'fitzcarraldo', 'juice', 'vincent', 'heights', 'precinct', 'addicted', 'gromit:', 'wing', 'flier', 'harvest', 'superweib', 'prizzis', 'mummy', 'something', '1961', 'muppets', 'mich', 'jean', 'fell', 'yol', 'penitentiary', 'tomb', 'goldfinger', 'ai', '1972', 'carrie', 'seventh', 'beautiful', 'girl?', 'shame', 'went', 'gesture', 'innocents', 'sur', 'bloodsport', 'heartburn', 'airport', 'pokémon:', 'sheik', 'looking', 'brothers', 'thomas', '1962', 'bushiko', 'shower', 'boondock', 'everything!', 'destino', 'supper', 'broke', 'fotoamator', 'slumber', 'george', 'will', 'habit', 'charlie', 'seventeen', 'liebster', 'zui', 'no', 'pumpkinhead', 'chasing', 'nature', 'madeline', 'isle', 'splash', 'fall', 'día', 'snatchers', 'lauderdale', 'drinking', 'steal', 'clouds', 'factory', 'juno', 'paths', 'place', 'lethal', 'almost', 'wizard', 'march', 'monument', 'airplane!', 'chucky', 'benjamenta', '1954', 'comedy', 'list', 'spanish', '60', 'flashdance', 'gigi', 'angus', 'rex', 'quartier', 'hallways', 'ognja', 'she-devil', 'eden', 'ned', 'blast', 'spring', 'mimic', 'west', 'belizaire', 'solar', 'las', 'worlds', 'noon', 'dansu?', 'mole', 'watership', 'ke', 'drunken', 'further', 'kaspar', 'peuple', 'rough', 'play', 'pagemaster', 'final', 'clockwatchers', 'uncut', 'santitos', 'knot', 'glimmer', 'jlg/jlg', 'beyrouth', 'children', 'butt-head', 'mephisto', 'candles', '1965', 'ravenous', 'fight', 'married', 'farmer', 'of', 'chungking', 'nineteen', 'devils', 'battlefield', 'gypsy', 'murder', 'adventures', 'parent', 'me', 'rubies', 'marty', 'guardano', 'pale', 'holy', 'coldblooded', 'schlafes', 'tianguo', 'shadow', 'iii:', 'concubine', 'vegas', 'memories', 'daens', 'standing', 'heathers', 'bud', 'leather', 'version', 'blackbeards', 'chacun', 'mat', 'making', 'liaison', 'lyndon', 'butchers', 'seul', 'or', 'cimarron', 'damien:', 'dolls', 'dog:', 'jesus', 'money', 'extremities', 'exit', 'searching', 'barry', 'short', 'kerle', 'leon:', 'afternoon', 'apocalypse', 'kids', 'law', 'harry', 'clause', 'baby-sitters', 'vichy', 'dietrich:', 'mirror', 'lamerica', 'chairman', 'ma', 'sequel', 'jam', 'cookies', 'flesh', 'schatten', 'sleeper', 'barbarella', 'hackers', 'lesbos', 'minds', 'scent', 'pane', 'disclosure', 'dinosaur', 'touch', 'shao', 'incognito', 'hak', 'bat', 'arena', 'demolition', 'holmes', 'cook', 'frisk', 'bananas', 'beautician', 'insomnia', 'proibito', 'strawberry', 'crimes', 'ghosts', 'jewel', 'crystal', 'cradle', 'parapluies', 'locomotive', 'nekromantik', 'gang', 'dracula', 'space', 'hugo', 'kidotai', 'kombat:', 'gary', 'traveller', 'rawhead', 'sherlock', 'hereafter', 'søndagsengler', 'assedio', 'kiss', 'va', 'greatest', 'znaleziony', 'noughts', 'eat', 'human', 'france', 'criminal', 'everyone', 'substance', 'teena', '52', 'twelve', '1942', 'loving', 'reunion', 'airheads', 'bliss', 'wore', 'domin', 'sematary', 'bacheha-ye', 'glenn', 'extreme', 'ligeia', 'rocketship', 'staircase', 'postino', 'shoulder', 'jerry', 'navigator', 'misery', 'realm', 'torchon', 'bones', 'curlys', 'mockingbird', 'death', 'manhattan', 'till', 'times', 'synthetic', 'jungle2jungle', '1982', 'hsing', 'castaway', 'face', 'dellamore', 'b*a*p*s', 'strangeland', 'inherit', 'judge', 'loose', 'beavis', 'bulworth', 'preachers', 'h20', 'fighting', 'texas', 'dawn', 'denver', 'solas', 'squad!', 'johns', 'devil', 'portrait', 'tijd', 'hamlet', 'temptation', 'burglar', 'personal', 'switchblade', 'superman', 'sleepy', 'streak', 'malkovich', 'storefront', 'outrageous', 'diary', 'hercules', 'miller', 'garbage', 'ponette', 'nénette', 'thoughts', 'fellow', 'upper', 'ciel', 'habits', 'nemo:', 'rings', 'conceiving', 'guardian', 'object', 'starr', 'buck', 'wolves', 'stelle', 'binds', 'flatbush', 'bulletproof', 'en', 'melody', 'coyote', 'beach', 'light', 'canadian', 'whom', 'frogs', 'dean', 'requiem', 'fearless', 'closet', 'festival', 'up', 'chat', 'circle', 'left', 'tex', 'klein', 'minus', 'paper', 'hard:', 'top', 'grape', 'veronique', 'dove', 'carlo', 'confess', 'silver', 'johnny', 'diabolique', 'cleaning', 'nashville', 'fauves', 'wend', 'mifunes', 'titans', 'stinks', 'fast', '1933', 'burning', '33', 'tai', 'steps', 'diva', 'cuts', '1923', 'bit', 'nikita', 'adams', 'kådisbellan', 'nervous', 'blink', 'freaky', 'shine', 'vivante', 'farinelli:', 'trust', 'civil', 'henge', 'any', 'sleepers', 'rosso', 'gate', 'ende', 'au', 'los', 'ideal', 'ringmaster', 'kokaku', 'pauline', 'leatherface:', 'simple', 'sixteen', 'hero', 'coups', 'lake', 'dame', 'brenda', 'fargo', 'summer', 'squall', '1964', 'happiest', 'scared', 'ropes', 'theodore', 'andrew', 'normal', 'you', 'amy', 'venice/venice', 'vieille', 'stag', 'fisher', 'hellraiser:', 'greenberg', 'sibak', 'tide', 'tomatoes', 'thats', 'sarafina!', 'peeping', 'sleepaway', 'moment', 'creature', 'are', 'cotton', 'cheerleader', 'shell', 'notte'

In [10]:
vocab = sorted(list(vocab))
print(vocab[:500])

['$1000000', '&', '-', '1', '1-900', '1/2', '1/2:', '1/3:', '10', '100', '101', '12', '13', '13th', '13th:', '1600', '17', '187', '1900', '1919', '1920', '1921', '1922', '1923', '1925', '1926', '1927', '1928', '1929', '1930', '1931', '1932', '1933', '1934', '1935', '1936', '1937', '1938', '1939', '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947', '1948', '1949', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1992:', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '1st', '2', '20', '200', '2000', '20000', '2001:', '2010', '20th', '24', '24-hour', '25', '28', '2:', '3', '3-d', '3000:', '301', '302', '33', '34th', '37th', '39', '3:', '3d', '4', '400', '42', '42nd', '45', '4:', '5', '52', '54', '5:', '6', '60', '66', '6:', '7', '77', '79', '7:', '7th', '8', '80', '81', '8mm', '8th', '9', '9000', '98', 'a', 'aardman', 'abbott', 'abbotts', 'abominable', 'about', 'above', 'abre', 'absent', 'absolute', 'abuelo', 'abyss', 'academy', 'access', 'accused', 'ace', 'aces:', 'acid', 'acres', 'across', 'act', 'action', 'actors', 'ada', 'adam', 'adams', 'addams', 'addicted', 'addiction', 'ado', 'adrenalin:', 'adventure', 'adventures', 'advocate', 'ae', 'affair', 'affection', 'affliction', 'afraid', 'africa', 'african', 'after', 'after:', 'afterglow', 'afternoon', 'again', 'against', 'age', 'agent', 'ages', 'agnes', 'agreement', 'agua', 'ai', 'aimée', 'aiqing', 'air', 'airheads', 'airplane', 'airplane!', 'airport', 'aka', 'akira', 'al', 'alabama', 'aladdin', 'alan', 'alarmist', 'alaska', 'albino', 'alexander', 'algiers', 'alice', 'alice/holy', 'alice?', 'alien', 'alien:', 'aliens', 'alien³', 'alive', 'all', 'allan', 'alles', 'alley', 'alligator', 'allnighter', 'almost', 'alone', 'alphaville', 'also', 'alvarez', 'always', 'am', 'amadeus', 'amantes', 'amants', 'amargo', 'amateur', 'amazing', 'america', 'american', 'americans', 'amigo/amado', 'amigos', 'amigos!', 'amistad', 'amityville', 'amityville:', 'among', 'amor', 'amos', 'amy', 'an', 'anaconda', 'analyze', 'anastasia', 'anatomie', 'anatomy', 'anchors', 'and', 'andre', 'andrew', 'andy', 'angefangen', 'angel', 'angela', 'angelas', 'angels', 'angels:', 'anges', 'angry', 'anguish', 'angus', 'angustia', 'animal', 'animation', 'anna', 'anne', 'annie', 'annihilation', 'another', 'ans', 'antonia', 'antonias', 'antonin', 'antz', 'any', 'anything', 'anywhere', 'août', 'aparajito', 'apart', 'apartment', 'ape', 'apes', 'aphrodite', 'apocalypse', 'apollo', 'apostle', 'appeal', 'apple', 'april', 'apt', 'apu', 'apur', 'arabia', 'arachnophobia', 'arc', 'arctic', 'are', 'arena', 'arguing', 'aristocats', 'arizona', 'ark', 'arlington', 'arm', 'armageddon', 'armed', 'arms', 'army', 'arnaud', 'around', 'arrest', 'arrival', 'arrivé', 'arrow', 'arsenic', 'art', 'artaud', 'artemisia', 'arthur', 'arthurs', 'as', 'aseman', 'asfour', 'ashes', 'asphalt', 'assassin', 'assassination', 'assassins', 'assault', 'assedio', 'assignment', 'assignment:', 'associate', 'astronauts', 'asylum', 'at', 'atlantic', 'attack', 'attacks!', 'attendent', 'attraction', 'au', 'aubrac', 'auch', 'audrey', 'august', 'aunt', 'auntie', 'aus', 'austin', 'autoportrait', 'autopsy', 'autumn', 'avalanche', 'ave', 'avenger', 'avengers', 'awake', 'awakenings', 'away', 'aweigh', 'awfully', 'axe', 'ayn', 'azucar', 'b', 'b*a*p*s', 'babe', 'babe:', 'babes', 'baby', 'baby-sitters', 'babyfever', 'babymother', 'babysitter', 'babysitting', 'bacheha-ye', 'bachelor', 'back', 'back!', 'backbeat', 'backdraft', 'bacon', 'bad', 'badkonake', 'badlands', 'badman', 'bag', 'baggage', 'baie', 'bait', 'baked', 'baker', 'balkan', 'ballad', 'balloon', 'ballou', 'ballroom', 'baloo', 'balto', 'bamba', 'bambi', 'bambini', 'bamboozled', 'bananas', 'band', 'bandit', 'bandits', 'bang', 'bank', 'bar', 'baraka', 'barb', 'barbarella', 'barbarian', 'barcelona', 'barefoot', 'barenaked', 'barneys', 'barrels', 'barry', 'bars', 'baruta', 'base', 'baseketball', 'basement!', 'basic', 'basketball', 'basquiat', 'bastard', 'bat', 'batch', 'bath', 'batman', 'batman:', 'baton', 'bats', 'battle', 'battlefield', 'battleship', 'battling', 'bay', 'bayou', 'be', 'beach', 'bean', 'beans', 'bear', 'beast', 'beat', 'beautician', 'beauties', 'beautiful', 'beauty', 'beaver', 'beavis', 'becomes', 'bed', 'bedknobs', 'bedlam', 'bedroom', 'bedrooms', 'beefcake', 'been', 'beetlejuice', 'before', 'beginning', 'behavior', 'beholder', 'being', 'beirut', 'belgians', 'beli', 'believers', 'belizaire']

Column Index

In [11]:
word_to_index = {}

for i, word in enumerate(vocab):
    word_to_index[word] = i

print(word_to_index["1"])

3

Create empty matrix

In [12]:
import numpy as np

num_docs = len(tokenized_docs)
num_words = len(vocab)

#count_matrix = np.zeros((num_docs,num_words))
#this produces error : Unable to allocate 33.9 GiB for an array with shape (1000209, 4546)
#and data type float64. so go with the following

count_matrix = np.zeros((num_docs,num_words),dtype=np.float64)

print(count_matrix.shape)

(3883, 4747)

In [13]:
count_matrix[:,0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(3883,))

In [14]:
from collections import Counter

for row_doc_index, doc in enumerate(tokenized_docs):
    word_count_dic = Counter(doc)
    for word in doc:
        col_word_index = word_to_index[word]
        count_matrix[row_doc_index][col_word_index] = word_count_dic[word]
print(count_matrix.shape)

(3883, 4747)

In [15]:
import pandas as pd

df_matrix = pd.DataFrame(
    count_matrix,
    columns=list(word_to_index.keys()),  # column names = words
    index=[f"Movie_{i}" for i in range(len(tokenized_docs))]  # row names = movies
)

print(df_matrix)

            $1000000    &    -    1  1-900  1/2  1/2:  1/3:   10  100  ...  \
Movie_0          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_1          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_2          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_4          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
...              ...  ...  ...  ...    ...  ...   ...   ...  ...  ...  ...
Movie_3878       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3879       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3880       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3881       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3882       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...

            zui  zulu  zwerge    à    á    è  école  émile  öga  über
Movie_0     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_1     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_2     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_4     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
...         ...   ...     ...  ...  ...  ...    ...    ...  ...   ...
Movie_3878  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3879  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3880  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3881  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3882  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0

[3883 rows x 4747 columns]

Initilizing tf_matrix

In [16]:
tf_matrix = np.zeros_like(count_matrix)

for i in range(num_docs):
    total_words = np.sum(count_matrix[i])
    if total_words != 0:
        tf_matrix[i] = count_matrix[i] / total_words
print(tf_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Compute df

In [17]:
print(len(count_matrix[6]))
print(count_matrix[5].shape)

4747
(4747,)

DF(t) = frequency of each words

In [18]:
df = np.zeros(num_words,)
df.shape
for i in range(num_words):
    df[i] = np.sum(count_matrix[:,i] > 0)
print(df)

[ 1. 40.  8. ...  1.  1.  1.]

N = total number of documents (constant)
IDF = log(N/df(t))

In [19]:
N = num_docs
idf = np.log(N/(df+1))

In [20]:
print("tf_matrix.shape : ",tf_matrix.shape)
print("idf.shape : ",idf.shape)
tfidf_matrix = tf_matrix * idf
print("tfidf_matrix : ",tfidf_matrix.shape)

tf_matrix.shape :  (3883, 4747)
idf.shape :  (4747,)
tfidf_matrix :  (3883, 4747)

Done the TF-IDF matrx. 

Now make a user profile to recommend to that user

Get User - 1 's high rated movies

In [23]:
user_id = 1
high_rated = ratings[(ratings['userId'] == user_id) & (ratings['rating'] >= 4)]
high_rated

    userId  movieId  rating  timestamp
0        1     1193       5  978300760
3        1     3408       4  978300275
4        1     2355       5  978824291
6        1     1287       5  978302039
7        1     2804       5  978300719
8        1      594       4  978302268
9        1      919       4  978301368
10       1      595       5  978824268
11       1      938       4  978301752
12       1     2398       4  978302281
13       1     2918       4  978302124
14       1     1035       5  978301753
15       1     2791       4  978302188
17       1     2018       4  978301777
18       1     3105       5  978301713
19       1     2797       4  978302039
22       1     1270       5  978300055
23       1      527       5  978824195
25       1       48       5  978824351
26       1     1097       4  978301953
27       1     1721       4  978300055
28       1     1545       4  978824139
30       1     2294       4  978824291
31       1     3186       4  978300019
32       1     1566       4  978824330
33       1      588       4  978824268
34       1     1907       4  978824330
35       1      783       4  978824291
36       1     1836       5  978300172
37       1     1022       5  978300055
38       1     2762       4  978302091
39       1      150       5  978301777
40       1        1       5  978824268
41       1     1961       5  978301590
42       1     1962       4  978301753
43       1     2692       4  978301570
44       1      260       4  978300760
45       1     1028       5  978301777
46       1     1029       5  978302205
47       1     1207       4  978300719
48       1     2028       5  978301619
49       1      531       4  978302149
50       1     3114       4  978302174
51       1      608       4  978301398
52       1     1246       4  978302091