In [2]:
import pandas as pd

ratings = pd.read_csv(
    "ml-1m/ratings.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["userId", "movieId", "rating", "timestamp"],
    header=None
)

movies = pd.read_csv(
    "ml-1m/movies.dat",
    sep="::",
    engine="python",
    encoding="latin-1",
    names=["movieId", "title", "genres"],
    header=None
)

In [3]:
movies.head()

   movieId                               title                        genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [4]:
ratings.head()

   userId  movieId  rating  timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [5]:
movies["content"] = movies["title"] + " " + movies["genres"].str.replace("|", " ")
movies.head()

,movieId,title,genres,content
0,1,Toy Story (1995),Animation|Children's|Comedy,Toy Story (1995) Animation Children's Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy,Jumanji (1995) Adventure Children's Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance,Grumpier Old Men (1995) Comedy Romance
3,4,Waiting to Exhale (1995),Comedy|Drama,Waiting to Exhale (1995) Comedy Drama
4,5,Father of the Bride Part II (1995),Comedy,Father of the Bride Part II (1995) Comedy

In [6]:
data = ratings.merge(movies, on="movieId")
data.head(20)

,userId,movieId,rating,timestamp,title,genres,content
0,1,1193,5,978300760,One Flew Over the Cuckoo's Nest (1975),Drama,One Flew Over the Cuckoo's Nest (1975) Drama
1,1,661,3,978302109,James and the Giant Peach (1996),Animation|Children's|Musical,James and the Giant Peach (1996) Animation Chi...
2,1,914,3,978301968,My Fair Lady (1964),Musical|Romance,My Fair Lady (1964) Musical Romance
3,1,3408,4,978300275,Erin Brockovich (2000),Drama,Erin Brockovich (2000) Drama
4,1,2355,5,978824291,"Bug's Life, A (1998)",Animation|Children's|Comedy,"Bug's Life, A (1998) Animation Children's Comedy"
5,1,1197,3,978302268,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance,"Princess Bride, The (1987) Action Adventure Co..."
6,1,1287,5,978302039,Ben-Hur (1959),Action|Adventure|Drama,Ben-Hur (1959) Action Adventure Drama
7,1,2804,5,978300719,"Christmas Story, A (1983)",Comedy|Drama,"Christmas Story, A (1983) Comedy Drama"
8,1,594,4,978302268,Snow White and the Seven Dwarfs (1937),Animation|Children's|Musical,Snow White and the Seven Dwarfs (1937) Animati...
9,1,919,4,978301368,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical,"Wizard of Oz, The (1939) Adventure Children's ..."
10,1,595,5,978824268,Beauty and the Beast (1991),Animation|Children's|Musical,Beauty and the Beast (1991) Animation Children...
11,1,938,4,978301752,Gigi (1958),Musical,Gigi (1958) Musical
12,1,2398,4,978302281,Miracle on 34th Street (1947),Drama,Miracle on 34th Street (1947) Drama
13,1,2918,4,978302124,Ferris Bueller's Day Off (1986),Comedy,Ferris Bueller's Day Off (1986) Comedy
14,1,1035,5,978301753,"Sound of Music, The (1965)",Musical,"Sound of Music, The (1965) Musical"
15,1,2791,4,978302188,Airplane! (1980),Comedy,Airplane! (1980) Comedy
16,1,2687,3,978824268,Tarzan (1999),Animation|Children's,Tarzan (1999) Animation Children's
17,1,2018,4,978301777,Bambi (1942),Animation|Children's,Bambi (1942) Animation Children's
18,1,3105,5,978301713,Awakenings (1990),Drama,Awakenings (1990) Drama
19,1,2797,4,978302039,Big (1988),Comedy|Fantasy,Big (1988) Comedy Fantasy

In [7]:
documents = movies['content'].fillna("").tolist()
print(type(documents))
print(documents[:10])

<class 'list'>
["Toy Story (1995) Animation Children's Comedy", "Jumanji (1995) Adventure Children's Fantasy", 'Grumpier Old Men (1995) Comedy Romance', 'Waiting to Exhale (1995) Comedy Drama', 'Father of the Bride Part II (1995) Comedy', 'Heat (1995) Action Crime Thriller', 'Sabrina (1995) Comedy Romance', "Tom and Huck (1995) Adventure Children's", 'Sudden Death (1995) Action', 'GoldenEye (1995) Action Adventure Thriller']

In [8]:
tokenized_docs = []

for doc in documents:
    doc = doc.lower()
    doc = doc.replace("(","").replace(")","")
    doc = doc.replace(",","").replace(".","")
    doc = doc.replace("'","")
    doc = doc.split()
    # print(words)
    # for word in words:
        # tokenizated_docs.append(word)
    tokenized_docs.append(doc)

print(tokenized_docs[:20])
print(len(tokenized_docs))

[['toy', 'story', '1995', 'animation', 'childrens', 'comedy'], ['jumanji', '1995', 'adventure', 'childrens', 'fantasy'], ['grumpier', 'old', 'men', '1995', 'comedy', 'romance'], ['waiting', 'to', 'exhale', '1995', 'comedy', 'drama'], ['father', 'of', 'the', 'bride', 'part', 'ii', '1995', 'comedy'], ['heat', '1995', 'action', 'crime', 'thriller'], ['sabrina', '1995', 'comedy', 'romance'], ['tom', 'and', 'huck', '1995', 'adventure', 'childrens'], ['sudden', 'death', '1995', 'action'], ['goldeneye', '1995', 'action', 'adventure', 'thriller'], ['american', 'president', 'the', '1995', 'comedy', 'drama', 'romance'], ['dracula:', 'dead', 'and', 'loving', 'it', '1995', 'comedy', 'horror'], ['balto', '1995', 'animation', 'childrens'], ['nixon', '1995', 'drama'], ['cutthroat', 'island', '1995', 'action', 'adventure', 'romance'], ['casino', '1995', 'drama', 'thriller'], ['sense', 'and', 'sensibility', '1995', 'drama', 'romance'], ['four', 'rooms', '1995', 'thriller'], ['ace', 'ventura:', 'when', 'nature', 'calls', '1995', 'comedy'], ['money', 'train', '1995', 'action']]
3883

In [9]:
vocab = set()
for doc in tokenized_docs:
    vocab.update(doc)
print(vocab)
print(len(vocab))

{'ferris', 'cinderella', 'öga', 'ramirez', 'spanish', 'greenberg', 'voyage', 'metal', 'mich', 'treat', 'rainmaker', 'laid', 'periscope', 'neon', 'us', 'swing', 'das', 'sematary', 'blues', 'paradise', 'pot', '1/3:', 'learning', 'sous-sol', 'newmar', 'rage:', 'anything', 'gattaca', 'asylum', 'hill', 'sphere', 'prophecy', 'firm', 'largo', 'lian', 'hendersons', 'trek:', 'che', 'ojos', 'chips', 'cave', 'battle', 'ooze', '1966', 'bound:', 'ghosts', 'milk', 'dove', 'kingpin', 'event', 'boondock', 'rim', 'castaway', 'bud:', 'fancy', 'logans', 'moon', 'amadeus', 'up!', 'hustler', 'piranha', 'truman', 'problem', 'karenina', 'stomper', 'potyomkin', 'seattle', 'trixie', 'me', 'gun:', 'hudsucker', 'chairs', 'stargate', 'singin', 'rendezvous', 'flew', 'natural', 'hunchback', 'crypt', 'sci-fi', 'hi-lo', 'fisher', 'drifter', 'stinks', 'abuelo', 'waterfront', 'cowboys', 'robocop', '1975', 'clay', 'zbogum', 'dance?', 'face/off', 'now', 'monty', 'rascals', 'farm', 'dazed', 'aristocats', 'extra-terrestrial', 'plennik', 'wrongfully', 'jimmy', 'lambs', 'rear', 'mascara', '400', 'duty', 'babe', 'tiffanys', 'daisy', 'mediaeval', 'gadget', 'candyman', 'streets', 'mirando', 'browne', 'cedars', 'roadside', 'jean', 'surviving', 'player', 'noirs', 'story', 'zoe', 'con', 'prendront', 'better', 'strangeland', '20000', 'recall', 'impact', 'incidents', 'student', 'portraits', 'afraid', 'fear', 'payback', 'aphrodite', 'shoes', 'films', 'drugstore', 'inherit', 'poison', 'sousatzka', 'willie', 'thin', 'swamp', 'lords', 'question', 'cries', 'poseidon', 'saucer', 'buddy', 'quilt', 'avenger', 'à', 'enough', 'nightmare', 'bloom', 'de', 'dundee', 'dieu&#8230;créa', 'caper', 'shaggy', 'ready', 'cookie', 'l', 'rattle', 'hi-yo', 'schlafes', 'twenty-five', 'hav', 'toy', 'zui', 'heroes', '9', 'eaten', 'center', 'retour', 'crime', 'stop!', 'rubies', 'like', 'carried', 'autoportrait', 'ni', 'en', 'america', 'nettoyage', 'indochine', 'smoking', 'basketball', 'food', 'bordeaux', 'd', 'drinking', 'round', 'bella', 'madeline', 'villa', 'fool', 'othello', 'crockett', 'native', 'otello', 'inventing', 'nô', 'quantestorie', 'palm', 'greasers', 'soylent', 'presents', 'planète', 'couple', 'vista', 'dom', 'attack', 'ground', 'conflict', 'state', 'caballeros', 'love:', 'playing', 'captain', 'lilians', 'prancer', 'bian', 'framed', 'mohicans', '302', 'ballou', 'facing', 'harmonists', 'affliction', 'welt', 'element', 'image', 'vita', 'guinevere', 'woman', 'fella', 'au', 'ideal', 'paradis', 'mina', 'gridlockd', 'laurel', 'près', 'from', 'rumble', 'pharaohs', 'follet', '1933', 'skulls', 'mnemonic', 'bridges', 'feeling', 'treasure', 'railroad', 'miller', 'fantasy', 'rising', 'enchanted', 'lost:', 'simply', 'providence', 'roof', 'action', 'prerokbe', 'hellhounds', 'alien', 'them', 'blown', 'jade', 'criminal', 'body', 'stacys', 'nice', 'alone', 'encino', 'tingle', 'carolina', 'nashville', 'eyre', 'placid', 'pocahontas', 'valour!', 'judy', 'joon', 'kids', 'washington', 'raging', 'bird', 'genius', 'related', 'bedrooms', 'julie', 'correspondent', 'icon', 'gilmore', 'bible', 'corrina', 'guildenstern', 'condorman', 'flight', 'ducks', 'magnificent', 'quatre', 'factory', 'striptease', 'no', 'inspector', 'homegrown', 'jail', 'cliffhanger', 'ponette', 'sibak', 'xi', 'distress', 'drunks', 'heartbreak', 'repossessed', 'puppet', 'european', 'schindlers', 'luke', 'i', 'bit', 'happen', 'tulsa', 'devil', 'waipo', 'manchurian', 'week', 'berlin', 'arsenic', 'hit', 'might', 'smiling', 'web', 'foreign', 'wicked', 'saving', 'matewan', 'bloody', 'haine', 'disco', 'howard', 'carlitos', 'minnie', 'crumb?', 'driver', 'bilder', 'garcu', 'játékos', 'wight', 'dates', 'ashes', 'check', 'anaconda', 'hots', 'shadow', 'ghostbusters', 'killer', 'charade', 'dumb', 'muir', 'presents:', 'macor', 'dinosaurs', 'closer', 'piano', 'dimension', 'saturday', 'marathon', 'arrow', 'wanda', 'navigator', 'sur', 'blackmail', 'fun', 'rio', 'lotto', 'guardano', 'shining', 'maîtres', 'crimson', 'neng', 'jones', 'final', 'analyze', 'inferno', 'following', 'loves', 'sparks', 'cemetery', 'adventure', 'nina', 'bernies', 'started', 'sherlock', 'etc', 'breaking', 'rekopis', 'hap', 'zwerge', 'haunting', 'dollars', 'thumb', 'step', 'bogus', 'parallel', 'possession', 'abbott', 'devils', 'nico', 'relic', 'gorgeous', 'freaky', 'mario', 'gloria', 'where', 'ce', 'picasso', 'baraka', 'casablanca', 'gumby:', 'vu', 'pimp', 'margarets', 'feind', 'preferred', '6', '9000', 'marlowe?', 'tijd', 'psycho', 'fluke', 'dreamlife', 'messenger:', 'clause', 'avalanche', 'row', 'spanking', 'germinal', 'knockout', 'singer', 'slate', 'jaws', 'lolita', 'crocodile', 'arena', 'roan', 'bud', 'network', 'sabbath', '3', 'falcon', 'she', 'maudit', 'apple', 'moreau', 'smell', 'aliens', 'couch', 'massacre', 'gould', 'bloodline', 'bad', 'american', 'secrets', 'reach', 'irma', 'braindead', 'ulees', 'hunted', 'rappaport', 'school', 'strike!', 'plunkett', 'batman:', 'bless', 'xinghua', 'swiss', 'crooklyn', 'innocents', 'prisoner', 'matrix', 'valley', 'ipcress', 'records', 'crow:', 'parker', 'blob', 'rider', 'fine', 'splash', 'brenda', 'jackie', 'french', 'fotoamator', 'bitter', 'loca', 'seconds', 'pump', 'guest', 'chop', 'mommie', 'musical', 'there', 'bachelor', 'tora!', 'fighting', 'dinner', 'firestorm', 'bulworth', 'deux', 'left', 'ice', 'dong', 'nick', 'apollo', 'heavyweights', 'muriels', 'vii:', 'mommas', 'microcosmos:', 'wonderland', 'faye', 'county', 'midaq', '1939', 'light', 'wind', 'promesse', 'beyrouth', '100', 'field', 'dust', 'mine', '1/2', 'cavalcade', 'rocketeer', 'krippendorfs', 'blechtrommel', 'access', 'heavens', 'grape', 'one-eye', 'shut', 'santa', 'william', 'pit', 'follia', 'runaway', 'lovers', 'hood:', 'fish', 'sex', 'ziegfeld', 'queen', 'wyn', 'storm', 'revolution', 'pacific', 'lagoon', 'nekromantik', 'amants', 'artemisia', 'kindred', 'nile', 'broke', 'sense', 'submarine', 'curtiss', 'vincent', 'dellesorcismo', 'hellbound:', 'jingle', 'bruce', 'stood', 'topsy-turvy', 'xiu:', 'combo', 'battlefield', 'colors', '2001:', '1960', 'turned', 'bleu', 'blank', 'strong', 'yue', 'ocean', '4', 'leagues', 'dogma', 'attendent', 'keys', 'do-right', '42', 'cairo', 'masters', 'finding', 'mitt', 'penny', 'pope', 'joes', 'candle', 'uninvited', 'rosencrantz', 'pride', 'until', 'bigalow:', 'camelot', 'speechless', 'enemy', 'episode', 'prizzis', 'upper', 'tracy', 'born', 'collants', 'collar', 'paradiso', 'nature', 'willy', 'versprechen', 'v:', 'legal', 'set', 'mosquito', 'monsieur', 'spaceballs', 'agent', 'cops', '1935', '37th', 'gotten', 'turkish', 'ado', 'film:', 'boiler', 'dogs', 'fallen', 'affection', 'holiday', 'glenda', 'cavo', 'celtic', 'his', 'mummys', 'coldblooded', 'back', 'thelma', 'frankie', 'reine', 'backdraft', 'serial', 'ransom', 'weiter', 'glimmer', 'melvin', 'binds', 'gung', 'dolls', 'scent', 'off', 'stepford', 'birdcage', 'let', 'hall', 'moonstruck', '1934', 'weint', 'passion', 'youre', 'klaka', 'halloween', 'territory', 'tomatoes!', 'pleasure', 'mercy', 'chamber', '1947', 'children', 'circle', 'un', 'east', 'arms', 'talks', 'spice', 'alphaville', 'asphalt', 'search', 'demented', 'measures', 'pork', 'wonka', 'bars', 'eight', 'mi', 'tease', 'dancers', 'meet', 'vinny', 'camp', 'pleasantville', 'move', 'why', 'different', 'anastasia', 'harvest', 'minnesota', 'hua', 'baseketball', 'it?', 'kerle', 'hillbillys', 'beach', 'bure', 'generals', 'zed', 'homeward', 'oz', 'rock', 'bean', 'gesture', 'paralyzing', 'mulan', 'scissorhands', 'company', 'marshalls', 'vampire', 'underground', 'dautomne', 'dirty', 'notre', 'choice', 'doom', '7', 'lightness', 'accused', 'mona', 'hime', 'peking', 'journals', 'terminator', 'whipped', 'douce', 'tuned', 'nuits', 'eraserhead', 'care', 'halbmond', 'joyriders', 'potemkin', 'show', 'red', 'bug', 'brain', 'capricorn', 'rebel', 'knight', 'kissing', 'x:', 'lord', 'rosemarys', 'grave', 'chef', 'died', 'huck', 'prey', 'mélodie', 'madam', 'cable', 'mall', 'echoes', 'zorro', 'goes', 'nel', 'chinois', 'vietnam', 'flanders', 'citizens', 'verdoux', 'prince', 'sneakers', 'say', 'nueba', 'yo', 'iris', 'wisdom', 'liebster', 'tre', 'stir', 'eclipse', 'midwinter', 'beloved/friend', 'titanic', 'deadly', 'bonnie', 'lesbos', 'stripes', 'slowly', 'end', 'majesty', 'kansas', 'career', 'sea', 'pi', 'nurse', '1981', 'gladiator', 'vanya', 'falkens', 'gay', 'roam', 'sleepless', 'jurassic', 'horse', 'coneheads', 'lifeboat', 'five', 'oasis', 'aka', 'six', 'arnaud', 'touch', 'sarajevo', 'grouchland', 'jewel', 'held', 'starlight', 'child', 'tights', 'vibes', 'babysitter', 'wishes', 'here', 'do', 'butterfly', 'cons', 'takes', 'tin', 'hope', 'spirits', 'chairman', '1929', 'lieutenant', 'reunion', 'golden', 'means', 'much', 'hoop', 'conformista', 'gospa', 'stupids', 'brasil', 'ruby', 'odyssey', 'quan', 'map', 'prisoners', 'madre', 'with', 'cents', 'airplane', 'feast', 'shentan', 'città', 'bicentennial', 'godfrey', 'deadtime', 'broadway', 'saw', 'carriers', 'sisters', 'rescue', 'ordinary', 'dans', 'crooks', 'bronenosets', 'falls', 'prom', 'pred', 'bus', 'captives', 'charlie', 'race', 'huozhe', 'vermeers', 'menace', '1970', 'unhook', 'gone', 'tarantella', 'kama', 'feu', 'graffiti', 'cheerleader', 'brockovich', 'collectionneuse', 'overdrive', 'girls', 'myers', 'santitos', 'aseman', 'fruit', 'locomotive', 'wagon', 'bliss', 'woo', 'bandit', 'room', 'pal', 'roustabout', 'sauce', 'lola', 'stelle', '1977', 'et', 'hear', 'devlin', 'benjamenta', 'nemo:', 'trail', 'dou', 'badlands', 'nadja', 'did', 'lisa', 'echte', 'floating', 'francisco', 'dragonheart', 'stranger', 'pauline', 'daytrippers', 'predator', 'priest', 'toxie', 'bewitched', 'swingers', 'everything', 'ticket', 'art', 'crying', 'gypsies', 'gremlins', 'lees', 'cujo', 'nuke', 'tell', 'jefferson', 'badkonake', 'mutiny', 'muscles', 'odd', 'client', 'case', 'senses', 'park:', '8th', 'invisible', 'education', 'roxbury', 'whole', 'taste', 'guantanamera', 'd2:', 'byrd', 'get', 'journey', '39', 'venus', 'committed', 'aus', 'jump', 'dr', 'notting', 'mansfield', 'screamers', 'mummy', 'unzipped', 'hui', 'medicine', 'baie', 'torn', '1931', 'squad', 'pajama', 'jim', 'zahlt', 'robbersons', 'anatomy', 'finzi-contini', 'hole', 'meatballs', 'bullets', 'dial', 'x', 'he', 'farewell', 'dave', 'halloween:', 'telling', 'angefangen', 'famous', 'something', 'hat', 'temptation', 'raining', 'side', '1940', 'jungle', 'live', 'sixth', 'nancy', 'cleo', 'mile', 'bell', 'mondo', 'illuminata', 'felicias', 'marvins', 'bay', 'gamma', 'return', 'pas', 'guys', 'photographer', 'zerkalo', 'fellow', 'ross', 'dear', 'kramer', 'joseph', 'western', 'cuts', 'videotape', 'harp', 'minors', 'morti', 'tetsuo', 'firestarter', 'maiment', 'brothers', 'johnson', 'railroaded!', 'renaissance', 'maguire', 'heaven', 'bomb', 'watership', 'ivy:', 'brasco', 'bushiko', 'sidste', 'shadrach', 'snowriders', 'named', 'calls', 'mom', 'beat', 'groove', 'picnic', 'dagosto', 'emerald', '1927', 'pick-up', 'champions', 'arthur', 'cutting', 'dinosaur', 'confessionnal', 'shakespeare', 'nightmares', 'goldfinger', 'hereafter', 'frances', 'toys', 'hackers', 'mrs', 'bananas', 'baton', 'spellbound', 'voleurs', 'ni-sen', 'pawnbroker', 'magnum', 'comforts', 'irene', 'juice', 'angels:', 'andrew', 'judgment', 'reilly', 'manon', 'pelham', 'heathers', 'shichinin', 'romy', 'charm', 'ulysses', 'taking', 'guns', 'anywhere', 'du', 'cousin', 'dunes', 'jaguar', 'bio-dome', 'square', 'own', 'tarantula', 'mission', 'gift', 'eraser', 'outside', 'puppetmaster', 'without', 'desire', 'hombre', 'mamma', 'sons', 'hostile', 'locusts', 'damien:', 'slipper', 'sleepaway', 'repo', 'jedi', 'effect', 'seven', 'hairy', '7:', 'alice?', '1963', 'jar', 'hund', 'babyfever', 'yes', 'iv:', 'sacco', 'navy', '13th:', 'parents', 'georgia', 'court', 'glass', 'professore!', 'lives', 'denise', 'ridge', 'raw', 'h20', 'mountains', 'wedding', 'lady', 'buena', 'tide', 'apes', 'grateful', 'lesson', 'sun', 'fools', 'amistad', 'computer', 'yojimbo', 'haunted', 'gentleman', 'flying', 'bond', 'down:', 'emma', 'sir', 'hawaii', 'switchback', 'jing', 'ratchet', 'betty', 'error', 'pinocchio', 'while', 'mute', 'destiny', 'shooter', 'tree', 'dîner', 'husband', 'horrors', 'secretaries', 'diario', 'deceit', 'speed', 'frogs', 'is', 'soldiers', 'bitch', 'guilty', 'robinson', 'across', 'wine', 'train', 'syn', 'sacrifice', 'waterworld', 'mob', 'bones', 'davy', 'win', 'zone', 'senior', '1999', 'umbrellas', 'quest', '1974', 'federal', 'airplane!', 'power', 'stay', 'collector', 'tafus', 'bullwinkle', 'escape', 'signals', 'travolti', 'cabinet', 'happy', 'martin', 'female', 'twilight', 'madison', 'oliver', 'wish', '1938', 'deconstructing', 'chapter', 'hall:', 'town', 'blink', 'phoenix', 'winds', 'illusion', 'jesus', 'horror', 'stakeout', 'sonja', 'how', 'nuit', 'boulevard', 'sirens', 'verge', 'nighthawks', 'cowboy', 'murderer', 'zachariah', 'screaming', 'blows', 'feiying', 'tail', 'jude', 'machine', 'wong', 'rebecca', 'secreto', 'crossing', 'insomnia', 'net', 'russia', 'jules', 'trigger', 'etz', 'flipper', 'el', 'species', 'superweib', 'flawless', 'angelas', 'retrouvé', 'control', 'belly', 'swept', 'neighbors', 'slappy', 'mowgli', 'clockwork', 'pail', 'marnie', '52', 'anne', 'damsel', 'mephisto', 'industry', 'formidable', 'created', 'd3:', 'polar', 'parenthood', 'chans', 'josey', 'artaud', 'wu', 'saimt', '2000', 'transit', 'caligula', 'cold', 'permanent', '200', 'guard', 'starman', 'documentary', 'broomsticks', 'grandfather', 'sec', 'mice', 'fort', 'film', 'incredibly', 'unhold', 'tomorrow', 'gypsy', 'heat', 'babes', 'year', 'turbo:', '1', 'replacements', 'agnes', 'tribe', 'bambi', 'bits', 'copycat', 'attraction', 'pollyanna', 'quartier', 'condition', 'baruta', 'leather', 'sierra', 'bread', 'wizard', 'texas', 'secret', 'lantern', 'peor', 'vieille', 'bewegte', 'burden', 'cookies', '80', 'dance', 'values', 'extreme', 'innocence', 'wanna', 'mirage', 'may', 'mississippi', 'em', 'grill', 'shelleys', 'gangstas', 'vie', 'junior', 'sugarland', 'bittersweet', 'bacon', 'clueless', 'le', 'smith', 'front', 'roseannas', 'crown', 'becomes', 'new', 'frenzy', 'sliver', 'dalloway', 'cotton', 'gila', 'fingerprints', 'seul', 'squeeze', 'tigrero:', 'ten', 'julien', 'ferne', 'kui', 'polish', 'assassins', 'amy', 'qin', 'bodyguard', 'theodore', 'island', 'wars:', 'gullivers', 'gillian', 'alien³', 'slaves', 'parasite', 'niezi', 'april', 'vek', 'nowhere', 'desperate', 'niagara', 'earth', 'ladybird', 'completely', 'jeremiah', 'toilet', 'kozlowski', 'slc', 'arthurs', 'sgt', 'sleep', 'distance', 'invitation', 'death', 'kind', 'orange', 'blame', 'chauffeur', 'purple', 'ilsa', 'coyote', 'lies', 'crush', 'loser', 'wilde', 'belle', 'arrival', 'birds', 'celluloid', 'thinner', 'samurai', 'conquered', 'chill', 'paul', 'everything!', 'within', 'coma', 'roger', 'sugar', 'fair', 'postino', 'fievel', '1988', 'viva', 'adam', 'giving', 'doubt', 'horses', '1987', 'limelight', 'woolf?', 'speriamo', 'excess', 'wild', 'heidi', 'their', 'bride', 'illtown', 'right', 'basic', 'conqueror', 'inn', 'dragons', 'underneath', 'more', 'heights', 'boogie', 'endless', 'harvey', 'low', 'crna', 'breathing', 'mildred', 'soapdish', 'steal', 'bobby', 'missing', 'illusions', 'bros', 'phantoms', 'suture', 'della', 'dersu', 'houseguest', 'virgin', 'mountain', 'anatomie', 'canadian', 'mccullochs', 'dantes', 'nutty', 'xue', 'governess', 'decision', 'glory', 'am', 'thriller', 'awfully', 'dragon', 'fu', 'airheads', 'boot', 'groundhog', 'stonewall', 'concorde:', 'yi', 'total', 'henry', 'hollywood', 'nella', 'brave', 'love', 'amor', 'threesome', 'alarmist', 'british', 'howards', 'boricuas', 'barenaked', '60', 'played', 'knew', 'mole', 'schizopolis', 'sommersby', 'monkeys', 'alien:', 'daughters', 'preacher', 'broadcast', 'everest', 'persuasion', 'working', 'distinguished', 'benji', 'delirio', 'insider', 'höstsonaten', 'nah!', 'moonraker', 'tibet', '7th', 'vengeance', 'courage', 'standing', 'endurance', 'precinct', 'juror', '1925', 'tannenbaum', 'slickers', 'conspiracy', 'generations', 'mockingbird', 'academy', 'baked', 'ladri', 'caught', 'joy', 'wall', 'october', 'expectations', 'highlander', 'falling', 'eye', 'shuang', 'roseanna', 'rings', 'assedio', 'coast', 'robin', 'phörpa', 'wally', 'tron', 'boy', 'bronco', 'foot', 'fanatic', 'risk', 'boni', 'pythons', 'graduate', 'big', 'johns', 'sprung', 'snows', 'claus:', 'vous', 'maker', 'tutor', 'anchors', 'false', 'office', 'edward', 'small', 'blind', 'months', 'alan', 'blast', 'beans', 'marked', 'ulisse', '13', 'voices', 'hurlyburly', 'chicken', 'garbage', 'und', 'outlaws', 'marchait', 'ci', 'ruth', 'fever', 'jesse', 'beefcake', 'lodger', 'gigolo', '42nd', 'ventura:', 'barbarella', 'grosse', 'dumbo', 'intelligence', 'habit', 'requiem', 'freejack', 'acres', 'fireworks', 'unbearable', 'corrida', 'conan', 'gigi', 'madonna:', 'lucinda', 'play', 'jakob', 'ceux', 'driving', 'weeks', 'hamam', 'redemption', 'pleasures', 'kwai', 'snakes', 'mediterraneo', 'loud', 'nobodys', 'fight', 'shampoo', 'wolf', 'men', 'after', 'wait', 'regained', 'still', 'antonia', 'rent-a-cop', 'farmers', 'green', 'snatchers', 'catastrophes', 'will', 'temple', 'topless', 'cristo', 'cabiria', 'sparrows', '1949', 'deer', 'sweet', 'duets', 'hour', 'pallbearer', 'lethal', 'air', 'lou:', 'sting', 'saint', 'uncut', 'ninth', 'ed', 'cléo', 'buckaroo', 'heart', 'kill', 'nest', 'exotica', 'justice', 'birthday', 'life', 'heads', 'almost', 'fury', 'burnt', 'hsing', 'kokaku', 'grumpier', 'tank', 'lay', 'sauvage', 'stalag', 'squad!', 'knot', 'perils', 'scout', 'halfmoon', 'fierce', 'honor', 'popeye', 'klumps', 'slaughterhouse', 'life!', 'first', 'painting', 'pie', 'major', 'freak', 'talk', 'thing', 'crackdown', 'alley', 'albino', 'smoke', 'glenn', 'shooting', 'violenza', 'eoniotita', 'trees', 'trouble', 'bat', 'annie', 'balto', 'pupil', 'august', '1995', 'forget', 'alligator', 'champagne', 'fries', 'regarde', 'reazione', 'se', 'remagen', 'basement!', 'scary', 'inish', 'karakter', 'bank', 'absolute', 'sleepy', 'future', 'pointe', 'burbs', 'affair', 'butcher', 'jardin', 'rose', 'gentlemans', 'random', 'sefid', 'perversions', 'mambo', 'romper', 'séparation', 'heavenly', 'ghost', 'movie!', 'mackennas', 'place', 'impossible', 'suicide', 'biciclette', 'sophies', 'mir', 'thomas', 'feet', 'exorcism', 'cause', 'homage', 'violin', 'flynt', 'crocodiles', 'lin:', 'twenty', 'liaisons', 'thousand', 'gromit:', 'birdy', 'sheep', 'this', 'geniuses', 'jeopardy', 'invasion', 'tie', '5', 'resurrection', 'crumb', '1982', 'hallways', 'traffic', 'dellamore', 'roberts', 'emperor', 'hercules', 'before', 'tough', 'rooms', 'cimarron', 'nain', 'violence', 'bamba', 'mikey', 'oblivion', 'unforgotten:', 'fright', 'á', 'so', 'phenomenon', 'hellraiser', '1926', 'tashunga', 'helena', 'buddha', 'filth', 'jennifer', 'someone', 'smile', 'china', 'cruel', 'could', 'mighty', 'sunrise', 'further', 'help!', 'heartburn', 'souls', 'sangre', 'gaslight', 'knock', 'boyfriends', 'way', 'core', 'history', 'hippie', 'frankenstein', 'heroin:', 'jupiters', 'turtle', 'outbreak', 'cyrano', 'apocalypse', 'devine', 'watcher', 'il', 'touki', 'morning', '1941', 'dreamed', 'supergirl', 'dudley', 'beneath', 'moll', 'believers', 'odessa', 'cupboard', 'carnival', 'jeffrey', 'bilko', 'miranda:', '1972', 'faust', 'graveyard', 'slayer', 'dracula', 'curtain', 'faraway', 'detective', '20th', 'curlys', 'vegas', 'brandon', 'sanjuro', 'tokyo', 'traveller', 'autumn', 're-animator', 'guffman', 'topaz', 'ugly', 'wore', 'free', 'st', 'les', 'lampoons', 'babe:', 'receiver', 'deliverance', 'flower', 'kelvin', 'made', 'three', 'jeanne', 'hangmen', 'cadillac', 'entertaining', '81', 'casino', 'angela', 'azucar', 'magoo', 'mort', 'lightfoot', 'romancing', 'bootmen', 'jackson', 'even', 'digging', 'second', 'octane', 'muppets', 'early', 'dutchman', 'glengarry', 'sonata', 'sabotage', 'metropolis', 'maurice', 'unknown', 'chuck', 'sequel', 'apt', 'hush', 'sing', 'todo', 'hook', 'va', 'sobre', 'goya', 'crew', 'sky', 'ville', 'omen', 'footloose', 'wend', 'kidotai', 'butch', 'marty', 'ridgemont', 'nervous', 'mariposas', 'disclosure', 'nil', 'louise', 'conformist', 'mourner', 'x-files:', 'peter', 'earrings', 'who', 'h

In [10]:
vocab = sorted(list(vocab))
print(vocab[:500])

['$1000000', '&', '-', '1', '1-900', '1/2', '1/2:', '1/3:', '10', '100', '101', '12', '13', '13th', '13th:', '1600', '17', '187', '1900', '1919', '1920', '1921', '1922', '1923', '1925', '1926', '1927', '1928', '1929', '1930', '1931', '1932', '1933', '1934', '1935', '1936', '1937', '1938', '1939', '1940', '1941', '1942', '1943', '1944', '1945', '1946', '1947', '1948', '1949', '1950', '1951', '1952', '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1992:', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '1st', '2', '20', '200', '2000', '20000', '2001:', '2010', '20th', '24', '24-hour', '25', '28', '2:', '3', '3-d', '3000:', '301', '302', '33', '34th', '37th', '39', '3:', '3d', '4', '400', '42', '42nd', '45', '4:', '5', '52', '54', '5:', '6', '60', '66', '6:', '7', '77', '79', '7:', '7th', '8', '80', '81', '8mm', '8th', '9', '9000', '98', 'a', 'aardman', 'abbott', 'abbotts', 'abominable', 'about', 'above', 'abre', 'absent', 'absolute', 'abuelo', 'abyss', 'academy', 'access', 'accused', 'ace', 'aces:', 'acid', 'acres', 'across', 'act', 'action', 'actors', 'ada', 'adam', 'adams', 'addams', 'addicted', 'addiction', 'ado', 'adrenalin:', 'adventure', 'adventures', 'advocate', 'ae', 'affair', 'affection', 'affliction', 'afraid', 'africa', 'african', 'after', 'after:', 'afterglow', 'afternoon', 'again', 'against', 'age', 'agent', 'ages', 'agnes', 'agreement', 'agua', 'ai', 'aimée', 'aiqing', 'air', 'airheads', 'airplane', 'airplane!', 'airport', 'aka', 'akira', 'al', 'alabama', 'aladdin', 'alan', 'alarmist', 'alaska', 'albino', 'alexander', 'algiers', 'alice', 'alice/holy', 'alice?', 'alien', 'alien:', 'aliens', 'alien³', 'alive', 'all', 'allan', 'alles', 'alley', 'alligator', 'allnighter', 'almost', 'alone', 'alphaville', 'also', 'alvarez', 'always', 'am', 'amadeus', 'amantes', 'amants', 'amargo', 'amateur', 'amazing', 'america', 'american', 'americans', 'amigo/amado', 'amigos', 'amigos!', 'amistad', 'amityville', 'amityville:', 'among', 'amor', 'amos', 'amy', 'an', 'anaconda', 'analyze', 'anastasia', 'anatomie', 'anatomy', 'anchors', 'and', 'andre', 'andrew', 'andy', 'angefangen', 'angel', 'angela', 'angelas', 'angels', 'angels:', 'anges', 'angry', 'anguish', 'angus', 'angustia', 'animal', 'animation', 'anna', 'anne', 'annie', 'annihilation', 'another', 'ans', 'antonia', 'antonias', 'antonin', 'antz', 'any', 'anything', 'anywhere', 'août', 'aparajito', 'apart', 'apartment', 'ape', 'apes', 'aphrodite', 'apocalypse', 'apollo', 'apostle', 'appeal', 'apple', 'april', 'apt', 'apu', 'apur', 'arabia', 'arachnophobia', 'arc', 'arctic', 'are', 'arena', 'arguing', 'aristocats', 'arizona', 'ark', 'arlington', 'arm', 'armageddon', 'armed', 'arms', 'army', 'arnaud', 'around', 'arrest', 'arrival', 'arrivé', 'arrow', 'arsenic', 'art', 'artaud', 'artemisia', 'arthur', 'arthurs', 'as', 'aseman', 'asfour', 'ashes', 'asphalt', 'assassin', 'assassination', 'assassins', 'assault', 'assedio', 'assignment', 'assignment:', 'associate', 'astronauts', 'asylum', 'at', 'atlantic', 'attack', 'attacks!', 'attendent', 'attraction', 'au', 'aubrac', 'auch', 'audrey', 'august', 'aunt', 'auntie', 'aus', 'austin', 'autoportrait', 'autopsy', 'autumn', 'avalanche', 'ave', 'avenger', 'avengers', 'awake', 'awakenings', 'away', 'aweigh', 'awfully', 'axe', 'ayn', 'azucar', 'b', 'b*a*p*s', 'babe', 'babe:', 'babes', 'baby', 'baby-sitters', 'babyfever', 'babymother', 'babysitter', 'babysitting', 'bacheha-ye', 'bachelor', 'back', 'back!', 'backbeat', 'backdraft', 'bacon', 'bad', 'badkonake', 'badlands', 'badman', 'bag', 'baggage', 'baie', 'bait', 'baked', 'baker', 'balkan', 'ballad', 'balloon', 'ballou', 'ballroom', 'baloo', 'balto', 'bamba', 'bambi', 'bambini', 'bamboozled', 'bananas', 'band', 'bandit', 'bandits', 'bang', 'bank', 'bar', 'baraka', 'barb', 'barbarella', 'barbarian', 'barcelona', 'barefoot', 'barenaked', 'barneys', 'barrels', 'barry', 'bars', 'baruta', 'base', 'baseketball', 'basement!', 'basic', 'basketball', 'basquiat', 'bastard', 'bat', 'batch', 'bath', 'batman', 'batman:', 'baton', 'bats', 'battle', 'battlefield', 'battleship', 'battling', 'bay', 'bayou', 'be', 'beach', 'bean', 'beans', 'bear', 'beast', 'beat', 'beautician', 'beauties', 'beautiful', 'beauty', 'beaver', 'beavis', 'becomes', 'bed', 'bedknobs', 'bedlam', 'bedroom', 'bedrooms', 'beefcake', 'been', 'beetlejuice', 'before', 'beginning', 'behavior', 'beholder', 'being', 'beirut', 'belgians', 'beli', 'believers', 'belizaire']

Column Index

In [11]:
word_to_index = {}

for i, word in enumerate(vocab):
    word_to_index[word] = i

print(word_to_index["1"])

3

Create empty matrix

In [12]:
import numpy as np

num_docs = len(tokenized_docs)
num_words = len(vocab)

#count_matrix = np.zeros((num_docs,num_words))
#this produces error : Unable to allocate 33.9 GiB for an array with shape (1000209, 4546)
#and data type float64. so go with the following

count_matrix = np.zeros((num_docs,num_words),dtype=np.float64)

print(count_matrix.shape)

(3883, 4747)

In [13]:
count_matrix[:,0]

array([0., 0., 0., ..., 0., 0., 0.], shape=(3883,))

In [14]:
from collections import Counter

for row_doc_index, doc in enumerate(tokenized_docs):
    word_count_dic = Counter(doc)
    for word in doc:
        col_word_index = word_to_index[word]
        count_matrix[row_doc_index][col_word_index] = word_count_dic[word]
print(count_matrix.shape)

(3883, 4747)

In [15]:
import pandas as pd

df_matrix = pd.DataFrame(
    count_matrix,
    columns=list(word_to_index.keys()),  # column names = words
    index=[f"Movie_{i}" for i in range(len(tokenized_docs))]  # row names = movies
)

print(df_matrix)

            $1000000    &    -    1  1-900  1/2  1/2:  1/3:   10  100  ...  \
Movie_0          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_1          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_2          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_4          0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
...              ...  ...  ...  ...    ...  ...   ...   ...  ...  ...  ...
Movie_3878       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3879       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3880       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3881       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...
Movie_3882       0.0  0.0  0.0  0.0    0.0  0.0   0.0   0.0  0.0  0.0  ...

            zui  zulu  zwerge    à    á    è  école  émile  öga  über
Movie_0     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_1     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_2     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_4     0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
...         ...   ...     ...  ...  ...  ...    ...    ...  ...   ...
Movie_3878  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3879  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3880  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3881  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0
Movie_3882  0.0   0.0     0.0  0.0  0.0  0.0    0.0    0.0  0.0   0.0

[3883 rows x 4747 columns]

Initilizing tf_matrix

In [16]:
tf_matrix = np.zeros_like(count_matrix)

for i in range(num_docs):
    total_words = np.sum(count_matrix[i])
    if total_words != 0:
        tf_matrix[i] = count_matrix[i] / total_words
print(tf_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

Compute df

In [17]:
print(len(count_matrix[6]))
print(count_matrix[5].shape)

4747
(4747,)

DF(t) = frequency of each words

In [18]:
df = np.zeros(num_words,)
df.shape
for i in range(num_words):
    df[i] = np.sum(count_matrix[:,i] > 0)
print(df)

[ 1. 40.  8. ...  1.  1.  1.]

N = total number of documents (constant)
IDF = log(N/df(t))

In [19]:
N = num_docs
idf = np.log(N/(df+1))

In [20]:
print("tf_matrix.shape : ",tf_matrix.shape)
print("idf.shape : ",idf.shape)
tfidf_matrix = tf_matrix * idf
print("tfidf_matrix : ",tfidf_matrix.shape)

tf_matrix.shape :  (3883, 4747)
idf.shape :  (4747,)
tfidf_matrix :  (3883, 4747)

Done the TF-IDF matrx. 

Now make a user profile to recommend to that user

Get User - 1 's high rated movies

In [21]:
user_id = 1
high_rated = ratings[(ratings['userId'] == user_id) & (ratings['rating'] >= 4)]
high_rated[:5]

   userId  movieId  rating  timestamp
0       1     1193       5  978300760
3       1     3408       4  978300275
4       1     2355       5  978824291
6       1     1287       5  978302039
7       1     2804       5  978300719

In [22]:
liked_movies_ids = high_rated['movieId']
liked_indices = movies[movies['movieId'].isin(liked_movies_ids)].index.tolist()

In [23]:
movies[movies['movieId'].isin(liked_movies_ids)]["title"]

0                                Toy Story (1995)
47                              Pocahontas (1995)
148                              Apollo 13 (1995)
257     Star Wars: Episode IV - A New Hope (1977)
523                       Schindler's List (1993)
527                     Secret Garden, The (1993)
584                                Aladdin (1992)
590        Snow White and the Seven Dwarfs (1937)
591                   Beauty and the Beast (1991)
604                                  Fargo (1996)
773           Hunchback of Notre Dame, The (1996)
907                      Wizard of Oz, The (1939)
926                                   Gigi (1958)
1009                            Cinderella (1950)
1015                          Mary Poppins (1964)
1016                                 Dumbo (1941)
1022                   Sound of Music, The (1965)
1081            E.T. the Extra-Terrestrial (1982)
1176       One Flew Over the Cuckoo's Nest (1975)
1189                 To Kill a Mockingbird (1962)
1226                    Dead Poets Society (1989)
1250                    Back to the Future (1985)
1267                               Ben-Hur (1959)
1506                               Ponette (1996)
1526                              Hercules (1997)
1672                               Titanic (1997)
1768               Last Days of Disco, The (1998)
1838                                 Mulan (1998)
1892                              Rain Man (1988)
1893                    Driving Miss Daisy (1989)
1949                                 Bambi (1942)
1959                   Saving Private Ryan (1998)
2225                                  Antz (1998)
2286                         Bug's Life, A (1998)
2329                Miracle on 34th Street (1947)
2623             Run Lola Run (Lola rennt) (1998)
2693                      Sixth Sense, The (1999)
2722                             Airplane! (1980)
2728                                   Big (1988)
2735                    Christmas Story, A (1983)
2849              Ferris Bueller's Day Off (1986)
3036                            Awakenings (1990)
3045                           Toy Story 2 (1999)
3117                     Girl, Interrupted (1999)
3339                       Erin Brockovich (2000)
Name: title, dtype: object

In [24]:
print(liked_indices)

for idx in liked_indices[:3]:
    print("Index:", idx)
    print("Movie title:", movies.iloc[idx]['title'])
    print("Vector shape:", df_matrix.iloc[idx].shape)
    print()

[0, 47, 148, 257, 523, 527, 584, 590, 591, 604, 773, 907, 926, 1009, 1015, 1016, 1022, 1081, 1176, 1189, 1226, 1250, 1267, 1506, 1526, 1672, 1768, 1838, 1892, 1893, 1949, 1959, 2225, 2286, 2329, 2623, 2693, 2722, 2728, 2735, 2849, 3036, 3045, 3117, 3339]
Index: 0
Movie title: Toy Story (1995)
Vector shape: (4747,)

Index: 47
Movie title: Pocahontas (1995)
Vector shape: (4747,)

Index: 148
Movie title: Apollo 13 (1995)
Vector shape: (4747,)

Build the User Profile Vector

In [25]:
user_profile = np.mean(tfidf_matrix[liked_indices],axis=0)
print(user_profile)

[0.         0.         0.01037118 ... 0.         0.         0.        ]

Compute Cosine Similarity (User vs All Movies)

In [26]:
user_norm = np.sqrt(np.sum(user_profile ** 2))
movie_norm = np.sqrt(np.sum(tfidf_matrix**2, axis=1))
dot_product = tfidf_matrix @ user_profile

similarities = dot_product / (user_norm * movie_norm)

similarity = np.nan_to_num(similarities)
similarity[1]

np.float64(0.1830199064650918)

Remove Movies Already Seen

In [27]:
similarity[liked_indices] = -1
# so these don't get recommendated

Get Top 10 Recommendations

In [28]:
top_ten_indices = np.argsort(similarity)[::-1][:10]
recommended_movies = movies.iloc[top_ten_indices]["title"]
print(recommended_movies)

3090           Fantasia 2000 (1999)
1642               Anastasia (1997)
2012     Little Mermaid, The (1989)
2023    Return of Jafar, The (1993)
1262                Fantasia (1940)
2027         Sleeping Beauty (1959)
360           Lion King, The (1994)
2009        Jungle Book, The (1967)
2490         King and I, The (1999)
2030       Song of the South (1946)
Name: title, dtype: object

Verifying output

In [ ]:
print(movies.iloc[liked_indices]["title"])

0                                Toy Story (1995)
47                              Pocahontas (1995)
148                              Apollo 13 (1995)
257     Star Wars: Episode IV - A New Hope (1977)
523                       Schindler's List (1993)
527                     Secret Garden, The (1993)
584                                Aladdin (1992)
590        Snow White and the Seven Dwarfs (1937)
591                   Beauty and the Beast (1991)
604                                  Fargo (1996)
773           Hunchback of Notre Dame, The (1996)
907                      Wizard of Oz, The (1939)
926                                   Gigi (1958)
1009                            Cinderella (1950)
1015                          Mary Poppins (1964)
1016                                 Dumbo (1941)
1022                   Sound of Music, The (1965)
1081            E.T. the Extra-Terrestrial (1982)
1176       One Flew Over the Cuckoo's Nest (1975)
1189                 To Kill a Mockingbird (1962)
1226                    Dead Poets Society (1989)
1250                    Back to the Future (1985)
1267                               Ben-Hur (1959)
1506                               Ponette (1996)
1526                              Hercules (1997)
1672                               Titanic (1997)
1768               Last Days of Disco, The (1998)
1838                                 Mulan (1998)
1892                              Rain Man (1988)
1893                    Driving Miss Daisy (1989)
1949                                 Bambi (1942)
1959                   Saving Private Ryan (1998)
2225                                  Antz (1998)
2286                         Bug's Life, A (1998)
2329                Miracle on 34th Street (1947)
2623             Run Lola Run (Lola rennt) (1998)
2693                      Sixth Sense, The (1999)
2722                             Airplane! (1980)
2728                                   Big (1988)
2735                    Christmas Story, A (1983)
2849              Ferris Bueller's Day Off (1986)
3036                            Awakenings (1990)
3045                           Toy Story 2 (1999)
3117                     Girl, Interrupted (1999)
3339                       Erin Brockovich (2000)
Name: title, dtype: object

In [33]:
print(similarity[top_ten_indices])
# this is pretty decent

[0.40740446 0.39698572 0.37820824 0.35804528 0.35721462 0.35063693
 0.34723844 0.33527492 0.32516881 0.32484944]

### Evaluation

Get user data

In [ ]:
user_id = 1

user_data = ratings[(ratings["userId"] == user_id)]
liked_movies = user_data[user_data["rating"] >= 4]
liked_movies.head(5)

   userId  movieId  rating  timestamp
0       1     1193       5  978300760
3       1     3408       4  978300275
4       1     2355       5  978824291
6       1     1287       5  978302039
7       1     2804       5  978300719